# Generated by Django 5.1.1 on 2024-10-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="images",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="projects.image"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="technologies",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="projects.tech"
            ),
        ),
    ]
