# Generated by Django 5.1.1 on 2024-10-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_alter_project_images_alter_project_technologies"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tech",
            options={
                "verbose_name": "Technology",
                "verbose_name_plural": "Technologies",
            },
        ),
        migrations.AlterField(
            model_name="project",
            name="hero_image",
            field=models.ImageField(
                default="img/website.png", upload_to="img/projects/"
            ),
        ),
    ]
