# Generated by Django 5.1.1 on 2024-10-10 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_project_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="images",
        ),
        migrations.AddField(
            model_name="image",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="projects.project",
            ),
            preserve_default=False,
        ),
    ]
