# Generated by Django 5.1.1 on 2024-10-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_remove_project_images_image_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="title",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
