# Generated by Django 5.1.2 on 2024-10-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0007_alter_project_hero_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="hero_image",
            field=models.ImageField(default="website.jpg", upload_to="img/projects/"),
        ),
    ]
