# Generated by Django 5.1.2 on 2024-10-25 09:54

import projects.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0009_alter_image_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=projects.models.CloudinaryField(
                max_length=255, validators=[projects.models.file_validation]
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="hero_image",
            field=projects.models.CloudinaryField(
                max_length=255, validators=[projects.models.file_validation]
            ),
        ),
    ]
