# Generated by Django 5.1.2 on 2024-10-25 10:08

import cloudinary.models
import projects.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0010_alter_image_image_alter_project_hero_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="hero_image",
            field=cloudinary.models.CloudinaryField(
                max_length=255,
                validators=[projects.models.file_validation],
                verbose_name="image",
            ),
        ),
    ]
