# Generated by Django 5.1.2 on 2024-10-25 12:38

import cloudinary.models
import projects.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0011_alter_project_hero_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255,
                validators=[projects.models.file_validation],
                verbose_name="image",
            ),
        ),
    ]
