# Generated by Django 5.1.2 on 2024-10-27 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_squashed_0012_alter_image_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="short_desc",
            field=models.CharField(
                blank=True,
                help_text="This text will go in the project_list cards",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(
                blank=True, help_text="This text will go in the project_list cards"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=50),
        ),
    ]
