# Generated by Django 5.1.2 on 2024-10-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0013_project_short_desc_alter_image_project_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(
                blank=True, help_text="This text will go in the project_detail page"
            ),
        ),
    ]
