repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/asottile/pyupgrade
  rev: v3.17.0
  hooks:
  - id: pyupgrade
    args:
    - --py312-plus
- repo: https://github.com/adamchainz/django-upgrade
  rev: 1.21.0
  hooks:
  - id: django-upgrade
    args: [--target-version, '5.1']
# - repo: https://github.com/djlint/djLint
#   rev: v1.35.2
#   hooks:
#   - id: djlint-reformat-django
#   - id: djlint-django
- repo: https://github.com/adamchainz/djade-pre-commit
  rev: 0.1.0
  hooks:
  - id: djade
    args: [--target-version, '5.1']
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.7
  hooks:
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix]
  - id: ruff-format
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.10
  hooks:
  - id: bandit
    args:
    - -c
    - pyproject.toml
    additional_dependencies: [toml==0.10.2]
- repo: local
  hooks:
  - id: rustywind
    name: rustywind Tailwind CSS class linter
    language: node
    additional_dependencies:
    - rustywind@latest
    entry: rustywind
    args: [--write]
    types_or: [html]

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-toml
    args: [--autofix]
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
# - repo: https://github.com/astral-sh/uv-pre-commit
#   rev: 0.4.16
#   hooks:
#   - id: pip-compile
#     name: pip-compile pyproject.toml
#     args: [pyproject.toml, -o, requirements.txt]
#   - id: pip-compile
#     name: pip-compile pyproject.toml --extra dev
#     args: [pyproject.toml, --extra, dev, -o, requirements-dev.txt]
