name: Tests Runner
on:
  push:
    branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-22.04
    env:
      ALLOWED_HOSTS: '*'
      DEBUG: on
      SECRET_KEY: a secret to everybody

    steps:
    - name: Get the code
      uses: actions/checkout@v3

    - name: Install Just
      uses: extractions/setup-just@v2
      with:
        github-token: ${{ secrets.MY_GITHUB_TOKEN }}

    - name: Install astral/uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        github-token: ${{ secrets.MY_GITHUB_TOKEN }}

    - name: Install Python
      run: uv python install 3.12

    - name: Install Packages
      run: just requirements

    - name: Test it
      run: just test
