name: Tests Runner
on:
  push:
    branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-22.04
    env:
      DJANGO_SETTINGS_MODULE: core.settings.test
      ADMIN_EMAIL: admin@example.com
      ALLOWED_HOSTS: '*'
      DEBUG: on
      MAILGUN_API_KEY: key-123
      MAILGUN_API_URL: http://localhost:8000
      MAILGUN_SENDER_DOMAIN: sandbox123.mailgun.org
      SECRET_KEY: a secret to everybody

    steps:
    - name: Get the code
      uses: actions/checkout@v3

    - name: Install astral/uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        github-token: ${{ secrets.MY_GITHUB_TOKEN }}

    - name: Install Python
      run: uv python install 3.12

    - name: Install Packages
      run: uv sync --all-extras

    - name: Test it
      run: uv run --config-setting COVERAGE_CORE=sysmon python -m pytest --reuse-db -s
