name: Tests Runner
on:
  push:
    branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-22.04
    env:
      ALLOWED_HOSTS: '*'
      DEBUG: on
      SECRET_KEY: a secret to everybody

    steps:
    - name: Get the code
      uses: actions/checkout@v3

    - name: Install Just
      uses: extractions/setup-just@v2
      with:
        github-token: ${{ secrets.MY_GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Python packages
      uses: yezz123/setup-uv@v4
      with:
        uv-venv: .venv
    - run: just requirements

    - name: Test it
      run: just test
